project:
  type: website

website:
  title: "VKC Lab Learning Sessions"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: Sessions
        menu:
          - text: "Session 1: PCA, PCR, PLS"
            href: sessions/01-pca-pcr-pls.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true